config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'records#index'

  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  telegram_webhooks TelegramController#, {token: Rails.configuration.bot_token, username: 'day_life_tracker_bot'}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :records
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    @record.user = current_user if user_signed_in?
    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:text)
    end
end

app/controllers/telegram_controller.rb
class TelegramController < Telegram::Bot::UpdatesController

  # https://habrahabr.ru/post/279179/

  def start(email=nil, *)
    message = if email && from
      user = User.find_by(email: email)
      if user
        user.update(telegram: from['id'].to_i)
        "Привет #{from['username']}! Телеграм и почта связаны, пишите, всё сохраним."
      else
        "Привет, #{from['username']}! Похоже, у вас ещё нет аккаунта."
      end
    else
      "Привет #{from['username']}! Введите правильный электронный адрес." if from
    end
    reply_with :message, text: message
  end

  def message(message)
    r = Record.create( user: User.find_by(telegram: from['id']), text: message['text'] )
    reply_with :message, text: r ? "Ок" : "Ошибка :("
  end

  def help(cmd = nil, *)
    message =
      if cmd
        help_for_cmd?(cmd) ? t(".cmd.#{cmd}") : t('.no_help')
      else
        t('.help')
      end
    reply_with text: message
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#main-navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'LifeTracker', root_path, class: 'navbar-brand'
    #main-navbar-collapse.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to current_user.email
          li
            = link_to 'Выйти', destroy_user_session_path, :method=>'delete'
        - else
          li
            = link_to 'Регистрация', new_user_registration_path
          li
            = link_to 'Войти', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title LifeTracker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'layouts/header'
    .container

      main
        = yield

app/views/records/_form.html.slim
= form_for(record) do |f|
  - if record.errors.any?
    #error_explanation
      h2
        = pluralize(record.errors.count, "error")
        |  prohibited this record from being saved:
      ul
        - record.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :text
    = f.text_field :text
  .actions
    = f.submit

app/views/records/edit.html.slim
h1
  | Editing Record
= render 'form', record: @record
= link_to 'Show', @record
|  |
= link_to 'Back', records_path

app/views/records/index.html.slim
section.records-container
  - if @records.count == 0
    .record.row
      .col-sm-12 No records
  - @records.each do |record|
    .record.row
      .col-sm-2.time= record.created_at.strftime('%d.%m %H:%M:%S')
      .col-sm-9.text= record.text
      .col-sm-1.text-right.destroy= link_to 'x', record, method: :delete, data: { confirm: 'Are you sure?' }

app/views/records/new.html.slim
h1
  | New Record
= render 'form', record: @record
= link_to 'Back', records_path

app/views/records/show.html.slim
p
  strong
    | Text:
  = @record.text
= link_to 'Edit', edit_record_path(@record)
|  |
= link_to 'Back', records_path